title: szetyng
name: Sze Tyng Lee
email: lee.szetyng@gmail.com
description: Electrical and electronic engineer.

baseurl: "" # if your site is located at /blog or /home, enter it here, otherwise leave it as '/'
url: ""

parallax_image_one: assets/images/laptop2.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/penang.jpg

project_one: VS Code IPE
project_one_description: Collaborated with Microsoft to create an interactive programming experience that combines the rich editor experience of Visual Studio Code with the interactive programming model of Jupyter Notebook.
project_one_url: https://github.com/lorenzo2897/vscode-ipe
project_one_icon: location_on

project_two: Spam Detection
project_two_description: Applied the theory learned in Introduction to Machine Learning to classify emails as either spam or ham.
project_two_url: https://github.com/szetyng/machine-learning-spam
project_two_icon: photo_camera


project_three: ARM Emulator
project_three_description: Wrote an ARM emulator in F# that is able to parse and simulate a subset of the ARM UAL instructions. Thoroughly tested against <a href="https://salmanarif.bitbucket.io/visual/" target="_blank">VisUAL</a>, a visual ARM emulator used in Introduction to Computer Architecture.
project_three_url: https://github.com/szetyng/HLP5
project_three_icon: hotel

project_four: AceCaddie
project_four_description: Used an accelerometer to build an IoT device that tracks golf scores automatically when attached to the golf club. The accompanying mobile app allows friends to compete against each other.
project_four_url: https://github.com/szetyng/embedded
project_four_icon: restaurant

project_five: SortBot
project_five_description: Implemented a classifier that uses machine vision to sort items into four different recycling categories for a self-sorting recycling machine. Aims to encourage recyling on the Imperial College London campus by awarding points to users through an accompanying mobile app.
project_five_url: http://www.ee.ic.ac.uk/guo.liew15/yr2proj/default.htm
project_five_icon: restaurant

project_six: 2048
project_six_description: Recreated the popular 2048 game in C++.
project_six_url: https://github.com/jameshamann/jekyll-material-theme
project_six_icon: restaurant

portfolio_heading: Projects
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

# skills:
#   - name: angularjs
#   - name: c
#   - name: cplusplus
#   - name: git
#   - name: github
#   - name: java
#   - name: javascript
#   - name: nodejs
#   - name: python
#   - name: typescript


icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/szetyng
linkedin: https://www.linkedin.com/in/leeszetyng/

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
