title: szetyng
name: Sze Tyng Lee
email: lee.szetyng@gmail.com
description: Software developer.

baseurl: "" # if your site is located at /blog or /home, enter it here, otherwise leave it as '/'
url: ""

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/penang.jpg

project_satu: Guardrails
project_satu_description: >
  Designed and built a multi-agent system simulator in F# to investigate the effects of having minimal 
  recognition of rights to self-organise (i.e. guardrails) on the sustainability of electronic institutions. Using 
  the method of sociologically-inspired computing, these institutions are designed according to the 
  <a href="https://en.wikipedia.org/wiki/Elinor_Ostrom#Design_principles_for_Common_Pool_Resource_(CPR)_institution" target="_blank">principles</a> 
  proposed by political economist, Elinor Ostrom.
project_satu_url: https://github.com/szetyng/Guardrails
project_satu_icon: restaurant

project_dua: CaterPillar
project_dua_description: >
  Developed a smart pill organiser to improve pill adherence and reduce medication errors among
  the elderly. The CaterPillar system involves an electronic pillbox and Android applications for
  tablets and smartwatches. It learns to provide adaptive reminders based on data regarding the 
  user's daily routines.
project_dua_url: https://github.com/elisaherme/CaterPillar
project_dua_icon: hotel

project_one: neuron
project_one_description: >
  Collaborated with Microsoft to create an extension for Visual Studio Code, which has since been 
  <a href="https://blogs.msdn.microsoft.com/pythonengineering/2018/11/08/data-science-with-python-in-visual-studio-code/?fbclid=IwAR3M5REwXMSCxgCCiqKez_cMJr4WVYYy1DA3UjjjnhpNGDluQiSo4GnhBk0" target="_blank">incorporated into their Python extension</a> 
  as part of their Data Science features. It combines the 
  rich experience of using the code editor with the interactive programming model of Jupyter notebook.
project_one_url: https://github.com/neuron-team/vscode-ipe
project_one_icon: location_on

project_two: Spam Detection
project_two_description: >
  Applied the theory learned in Introduction to Machine Learning to classify emails as either spam or ham.
project_two_url: https://github.com/szetyng/machine-learning-spam
project_two_icon: photo_camera


project_three: ARM Emulator
project_three_description: >
  Wrote and fully tested an ARM emulator in F#. The programme is able to parse and consecutively simulate a subset of the 
  ARM UAL instructions. Aimed to recreate <a href="https://salmanarif.bitbucket.io/visual/" target="_blank">VisUAL</a>,
  a visual ARM emulator used in Introduction to Computer Architecture in Imperial College London as an aide in teaching the
  ARM assembly language.

project_three_url: https://github.com/szetyng/HLP5
project_three_icon: hotel

project_four: AceCaddie
project_four_description: >
  Used an accelerometer to build an IoT device that tracks golf scores automatically when it is 
  attached to the golf club in use. The accompanying mobile app allows friends to compete against each other.
project_four_url: https://github.com/szetyng/embedded
project_four_icon: restaurant

project_five: SortBot
project_five_description: >
  Implemented a classifier that uses machine vision to sort items into four different recycling categories 
  for a self-sorting recycling machine. Aims to encourage recyling on the Imperial College London campus by 
  awarding points to users of the machine through an accompanying mobile app.
project_five_url: https://github.com/szetyng/sortbot
project_five_icon: restaurant

project_six: 2048
project_six_description: Recreated the popular 2048 game in C++.
project_six_url: https://github.com/szetyng/2048
project_six_icon: restaurant

portfolio_heading: Projects
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

# skills:
#   - name: angularjs
#   - name: c
#   - name: cplusplus
#   - name: git
#   - name: github
#   - name: java
#   - name: javascript
#   - name: nodejs
#   - name: python
#   - name: typescript


icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/szetyng
linkedin: https://www.linkedin.com/in/leeszetyng/

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
